### ISSUE TITLE
pyrevolve installation error: Failed building wheel for pyrevolve: conflicting types for ‘_xgetbv’

### ISSUE THREAD

**Issue by dlight** [devitocodes/pyrevolve#42]
While creating the conda environment for devito, pip fails with `error: conflicting types for ‘_xgetbv’`.

Full output at:

https://gist.github.com/dlight/9c4854d9ab49e171f6da39335fd31d48

**Comment by dlight** [comment]
On Slack (at #installation) @navjotk replied about this workaround for AMD zen processors: https://github.com/Blosc/python-blosc/issues/203 (even though my processor isn't AMD - it supports avx2 but apparently this is broken on blosc)

So, this worked:

```
DISABLE_BLOSC_AVX2=1 conda env create -f environment.yml
conda activate devito
DISABLE_BLOSC_AVX2=1  pip install -e .
```

**Comment by navjotk** [comment]
I believe we fixed the error using the fix suggested at https://github.com/Blosc/python-blosc/issues/203 . Can we close this now?
