### ISSUE TITLE
python setup.py build_ext --inplace 

### ISSUE THREAD

**Issue by summerinternship2019** [devitocodes/pyrevolve#43]
running build_ext
building 'pyrevolve.crevolve' extension
gcc -pthread -B /home/miguel/anaconda3/envs/devito/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./pyrevolve -I. -Ipyrevolve -I/home/miguel/anaconda3/envs/devito/include/python3.7m -c pyrevolve/crevolve.cpp -o build/temp.linux-x86_64-3.7/pyrevolve/crevolve.o
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command 'gcc' failed with exit status 1

**Comment by navjotk** [comment]
What OS is this on? Compiler version?

**Comment by summerinternship2019** [comment]
HI 
 I use Ubuntu and run most of those code in the cluster
