### ISSUE TITLE
Support data that is not a numpy array

### ISSUE THREAD

**Issue by jhueckelheim** [devitocodes/pyrevolve#5]
The checkpoint storage in pyrevolve is a big numpy array, and the "pointers" that are given to `checkpoint.save(ptr)` and `checkpoint.load(ptr)` are in fact slices of that numpy array. A user who needs to store data that is not numpy will be out of luck. Not sure if this is really a problem in need of a fix, unless someone wants to do mixed-precision computing or checkpoint non-floating-point data. Open for discussion.

**Comment by navjotk** [comment]
I believe we have addressed this in the latest release since the compressed data is no longer a numpy array.
